version: '3'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: always
