version: '3'

services:
  frontend:
    build: ./frontend
    container_name: frontend

  backend:
    build: ./backend
    container_name: backend

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
