services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    networks:
      net:
        - ipv4_address: 192.168.240.2

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    networks:
      net:
        - ipv4_address: 192.168.240.3

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      net:
        - ipv4_address: 192.168.240.4

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.240.0/24